name: Release Font

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      cn:
        description: 'Include Chinese version (add "--cn" to build args)'
        required: false
        default: false
        type: boolean
      feat:
        description: 'Enable features, split by "," (add "--feat feat1,feat2" to build args)'
        required: false
        default: ''
        type: string
      build_args:
        description: 'Args for build.py'
        required: false
        default: ''
        type: string
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      # - name: Checkout branch
      #   run: git checkout main

      - name: Install ftcli
        run: pip install -r requirements.txt

      - name: Run release script
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            python release.py
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            set +e
            git add woff2
            git commit -m "Update woff2"
            git push
          else
            build_args="${{ github.event.inputs.build_args }} --archive"
            if [ ${{ github.event.inputs.cn }} ]; then
              build_args="$build_args --cn"
            fi
            if [ ${{ github.event.inputs.feat }} ]; then
              build_args="$build_args --feat ${{ github.event.inputs.feat }}"
            fi
            python build.py $build_args
          fi

      - name: Create release
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            TAG=${{ github.ref_name }}
            echo "$TAG" >> NOTES
            FILES=release/*.*
            STATUS="--draft"
            NOTES="--notes-from-tag"
          else
            TAG="v$(date +%s)"
            echo "$TAG" >> NOTES
            echo "### Build arguments\n\n${{ github.event.inputs.build_args }}" >> _NOTES
            echo "### Configuration\n\n```\n$(python build.py ${{ github.event.inputs.build_args }} --dry)\n```" >> _NOTES
            FILES=fonts/archive/*.*
            STATUS=""
            NOTES="--notes-file _NOTES"
          fi
          CMD="gh release create \"$TAG\" $FILES --generate-notes $NOTES $STATUS --target variable"

          # Debug the command
          echo "Executing command: $CMD"

          # Execute the command
          eval "$CMD"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
